### ISSUE TITLE
nomad_systemvinit.j2 issues

### ISSUE THREAD

**Issue by awheeler** [brianshumate/ansible-nomad#10]
Hey Brian,
the nomad_sysvinit.j2 file is passing `-pid-file "${PID_FILE}"` which nomad doesn't seem to recognize, and I can't find that arg in any 0.5.6 docs.

Additionally, restart doesn't seem to work, but stop, sleep for some period, and start does.  I've seen this behavior in other procs like consul, and I'm not sure what's causing it.

**Comment by brianshumate** [comment]
Fixed in b0552c5
