### ISSUE TITLE
Custom nomad config support

### ISSUE THREAD

**Issue by awheeler** [brianshumate/ansible-nomad#11]
Hi Brian,
I don't see a way to provide custom / local configs, like a consul token, since the daemon is started with explicit config files, rather than pointing to the config directory.
If the client and server configs were only placed based on the value of `nomad_node_role`, it would seem we could point to the config directory instead, and I could just create a consul.hcl file which would automatically be picked up.
Alternatively, a second config dir could be passed on to the daemon, leaving the existing setup intact.

Thoughts?

**Comment by brianshumate** [comment]
This can be done the same way [it was done in ansible-consul](https://github.com/brianshumate/ansible-consul/blob/master/tasks/config.yml#L52-L61)

**Comment by awheeler** [comment]
I agree, however it looks like I don't need to have any special config for consul, but I will when I add vault integration.
I can make the suggested change and submit a pull request if you like.

**Comment by brianshumate** [comment]
That sounds good to me, thanks!

**Comment by brianshumate** [comment]
Hi Alex,

Thanks for offering to do the PR for this! I assigned the issue to you and will be happy to review it.

Regards,

Brian

**Comment by awheeler** [comment]
You're welcome Brian.  Let me know what you think.

**Comment by brianshumate** [comment]
Fixed by #14 

Thanks again, Alex!
