### ISSUE TITLE
The server config is being installed on clients and ignored

### ISSUE THREAD

**Issue by awheeler** [brianshumate/ansible-nomad#18]
In the rendering of the server.hcl file, server specific variables are evaluated as well as needing the python-netaddr package, both of which may not be available to the client, requiring them to be defined or installed and then ignored.

I will create a merge request that address this by not installing the server.hcl file when nomad_node_role == 'client'

**Comment by brianshumate** [comment]
👍 Thanks for reporting this and for the PR, @awheeler!

I'll go ahead and close this now.
