### ISSUE TITLE
stopping nomad with SIGKILL

### ISSUE THREAD

**Issue by akostyrev** [brianshumate/ansible-nomad#2]
Hi Brian!
I've noticed that in [here](https://github.com/brianshumate/ansible-nomad/blob/master/templates/nomad_sysvinit.j2#L54) you are stopping nomad with SIGKILL signal.
Is it a recommended way to stop nomad?

**Comment by brianshumate** [comment]
Hi!

That's probably a holdover from older times and should be fixed.

By default, any signal to a Nomad agent (interrupt, terminate, kill) will cause the agent to forcefully stop anyway. I need to handle termination with `leave_on_interrupt` or `leave_on_terminate` in the server configuration and fix up that init script.

Sorry for huge lag; I was not watching this repo 😬

**Comment by brianshumate** [comment]
Fixed in release 1.4.5

Thanks again for the report!
