### ISSUE TITLE
Lost nomad_use_consul functionality

### ISSUE THREAD

**Issue by awheeler** [brianshumate/ansible-nomad#20]
With this commit: https://github.com/brianshumate/ansible-nomad/commit/8828144807c6a09c21ac420e82bd47f0433bb562
We lost the ability to auto-configure nomad based on consul.  Let's bring that back, unless there was a good reason to drop it.

If you agree, I'll submit a merge request.

**Comment by groggemans** [comment]
:+1:  Can't remember if this was an accident or that I did it on purpose with the idea of bringing it back later. But I'd like to see the functionality back either way :)

**Comment by awheeler** [comment]
Thanks for accepting the merge, closing.
