### ISSUE TITLE
bootstrap_expect not getting set properly when using Consul

### ISSUE THREAD

**Issue by kjagiello** [brianshumate/ansible-nomad#23]
Hello there!

I'm trying to setup a small development cluster, but have encountered some problems with the Nomad nodes not being able to elect a leader. The important factor contributing to this problem is that I'm using Consul – without it, the setup is smooth and painless.

I've narrowed down the issue to following code parts: 

`nomad_servers` will be set to the length of the array containing the hosts in the `nomad_group_name` group.
https://github.com/brianshumate/ansible-nomad/blob/40fa2bbe95c592d215f36be72d480accbe151fb2/templates/server.hcl.j2#L4-L6

The array will be however populated only if `nomad_use_consul=no`, which means that if Consul is enabled, the `bootsrap_expect` parameter will become 0, which confuses Nomad a lot and prevents it from electing leader (0 = no leader should be elected).
https://github.com/brianshumate/ansible-nomad/blob/418fa2ede73ed7240b37ef7cbc5af4c4dcf6405f/defaults/main.yml#L92-L104

Wouldn't it make sense to remove the surrounding if-statement in the snippet above? Even if you use Consul, you will want to maintain a list of the server nodes, so populating the `nomad_servers`, no matter the Consul presence, feels fine to me. What do you think?

```
nomad_servers: "\
  {% set _nomad_servers = [] %}\
  {% for host in groups[nomad_group_name] %}\
    {% set _nomad_node_role = hostvars[host]['nomad_node_role'] | default('client', true) %}\
    {% if ( _nomad_node_role == 'server' or _nomad_node_role == 'both') %}\
      {% if _nomad_servers.append(host) %}{% endif %}\
    {% endif %}\
  {% endfor %}\
  {{ _nomad_servers }}"
```

If you are fine with the proposed change, I will submit a PR with a fix.

Cheers!

**Comment by groggemans** [comment]
Nice catch! If I'm not mistaken, we just shouldn't set the bootstrap expect parameter when using consul. Because we don't know how many/which nodes will be discovered through consul. This can include nodes not configured by this role, and it should still work just fine.

If you could do a test with the `bootstrap_excpect` parameter not set when using consul that would be awesome! (Adding an if statement in the config template should be fine)

**Comment by kjagiello** [comment]
According to the Nomad docs, one should set `bootstrap_expect` so that Nomad knows how many servers to expect.

> For servers, we must inform the cluster how many servers we expect to have. This is required to form the initial quorum, since Nomad is unaware of how many peers to expect. 

https://www.nomadproject.io/guides/cluster/automatic.html

**Comment by groggemans** [comment]
Seems you're right, thanks for linking the relevant docs!

Populating it either way would be fine for me, but we might want to add a custom override value too, in case not all servers will be managed by the role.

A PR would be awesome!
