### ISSUE TITLE
Using this role, can we install nomad as any user

### ISSUE THREAD

**Issue by kramasamy** [brianshumate/ansible-nomad#29]
other than root? If nomad functionality is restricted to running jobs (with raw_fork/exec) it is fine.

**Comment by brianshumate** [comment]
Hi,

You can use any [user or group](https://github.com/brianshumate/ansible-nomad/blob/master/defaults/main.yml#L29-L33) you wish, but keep in mind that the best practice is to run Nomad **client agents** as `root` and server agents can run as a non-root user.

While you can run Nomad client agents as non-root users, only the Docker and raw_exec drivers will work, but some some functionality like the `/secrets` tmpfs will not work with a non-root user.

Hope that helps.

**Comment by brianshumate** [comment]
I'm going to go ahead and close this now as I think I answered your question.
