### ISSUE TITLE
Nomad will only log to /var/log/messages (RHEL7)

### ISSUE THREAD

**Issue by zswanson** [brianshumate/ansible-nomad#39]
I'm trying to get the role to configure nomad to log in /var/log/nomad rather than /var/log/messages, just for convenience of monitoring the cluster logs. I've set group_vars for my nomad group to:

```yaml
nomad_syslog_enable: false
```
and otherwise am using the default location for logging. Regardless of the syslog setting though, all log messages from nomad are written to /var/log/messages rather than the default location specified in the role as:
```yaml
nomad_log_dir: /var/log/nomad
```

**Comment by brianshumate** [comment]
Hi!

Unfortunatley, the `nomad_log_dir` configuration was invalid.

Nomad logs only to stdout/stderr in a 12 factor app style, which is captured by the systemd journal by default on most Linux distributions including RHEL7.

Nomad doesn't actually have configuration to specify logging to a static file location so I've removed the non-functional configuration and related documentation and apologies for the confusion there!
