### ISSUE TITLE
Please create a new release and update galaxy

### ISSUE THREAD

**Issue by ncabatoff** [brianshumate/ansible-nomad#52]
The role on galaxy is at 1.8.0, which is broken for me due to not having this fix: https://github.com/brianshumate/ansible-nomad/commit/e45d6b6278dd76ba80c64ed3576899c913dc4285

As a result I get errors like: 
```
AnsibleUndefinedVariable: 'nomad_ports_http' is undefined
```

**Comment by brianshumate** [comment]
Done!

**Comment by ncabatoff** [comment]
Thanks, works now!
