### ISSUE TITLE
Nomad installation error

### ISSUE THREAD

**Issue by crackmind** [brianshumate/ansible-nomad#53]
Hi All,

I am new to this website and getting nomad installation error even with admin rights.
![nomad installation error](https://user-images.githubusercontent.com/47586138/52691150-eaebf980-2f85-11e9-8581-d0882bebdd0f.png)

**Comment by brianshumate** [comment]
Hello!

I am not familiar with **Convert to NoMAD**.

It is not part of this project and we do not have a graphical installer as shown in your screenshot.

Perhaps there is a different project that makes such an installer?
