### ISSUE TITLE
Clarification regarding Consul

### ISSUE THREAD

**Issue by asemt** [brianshumate/ansible-nomad#6]
Hi,

that's a very clean role, thank you for all the effort you put into it!

I have a question, though:
In `tasks/install.yml` there's the `Download nomad` task with [this conditional check in line 45](https://github.com/brianshumate/ansible-nomad/blob/master/tasks/install.yml#L45):
```
when: consul_package.stat.exists == False
```
Does that mean the role is not meant to be used with Consul integration?
I'm asking this because I would like to use this role together with Consul [as described here](https://www.nomadproject.io/docs/agent/configuration/consul.html) for automatic service discovery of the tasks executed by Nomad.

**Comment by brianshumate** [comment]
Hey there,

Thanks for the kind words.

That's actually a typo/bug! It should be `when: nomad_package.stat.exists == False`. Thanks for the catch! I've fixed this in version 1.4.4 and will add you to CONTRIBUTORS for spotting this.

This role definitely works with Consul.

**Comment by asemt** [comment]
> This role definitely works with Consul.

Very cool!
Glad I could help.
