### ISSUE TITLE
The variable nomad_bin_dir is ignored

### ISSUE THREAD

**Issue by awheeler** [brianshumate/ansible-nomad#8]
All of the startup scripts are hard-coded for /usr/local/bin/nomad, but should instead use:
 ```{{ nomad_bin_dir }}/nomad```
And the install.yml file task (Install Nomad) also installs to `/usr/local/bin`, rather than `"{{ nomad_bin_dir }}"`

**Comment by brianshumate** [comment]
Updated!

**Comment by awheeler** [comment]
Thank you Brian -- really appreciate the quick turnaround.  Alas the install.yml use of /usr/local/bin - https://github.com/brianshumate/ansible-nomad/blob/master/tasks/install.yml#L53 was missed.
